### ISSUE TITLE
Before publishing

### ISSUE THREAD

**Issue by yannham** [tweag/nickel-lang.org#1]
# Todos

cc @garbas 

## Blocking

 - [x] Logo + palettes (ask Mickael)
 - [x] Apply design: fonts (1. logo 2. titles 3. normal text 4. code), colors
 - [x] Merge the WASM branch (Yann)
 - [x] Remove documentation page (Yann)
 - [x] Landing page (integrate playground)
 - [x] Update the getting-started page (use embedded playgrounds)
 - [x] Review all of existing text/content

## Non-blocking

 - [x] Bring in the website (or not) and use nickel-repl (Rok)
 - [ ] Update README (Note: check out [readme.so](https://readme.so))
 - [ ] Build the WASM automatically (Rok)

**Comment by mboes** [comment]
@yannham Obsolete?

**Comment by yannham** [comment]
Yep.
